# Generated by Django 5.2.9 on 2026-01-25 00:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='end_date',
            new_name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='man_days',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='service_request',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='specialist_id',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='specialist_name',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='winning_offer',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='current_contract_value',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='current_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='current_man_days',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='current_specialist_id',
            field=models.CharField(default='someid', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='current_specialist_name',
            field=models.CharField(default='somename', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='domain',
            field=models.CharField(default='somedomain', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='original_contract_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='original_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='original_man_days',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='original_specialist_id',
            field=models.CharField(default='some id', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='original_specialist_name',
            field=models.CharField(default='somename', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='role',
            field=models.CharField(default='somerole', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service_request_id',
            field=models.CharField(default='someid', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='supplier_id',
            field=models.CharField(default='someid', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='supplier_name',
            field=models.CharField(default='somename', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='winning_offer_id',
            field=models.CharField(default='someid', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended'), ('PENDING_EXTENSION', 'Pending Extension'), ('PENDING_SUBSTITUTION', 'Pending Substitution')], default='ACTIVE', max_length=30),
        ),
        migrations.CreateModel(
            name='ServiceOrderExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_SUPPLIER', 'Pending Supplier Approval'), ('PENDING_CLIENT', 'Pending Client Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_SUPPLIER', max_length=30)),
                ('additional_man_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('new_end_date', models.DateField()),
                ('additional_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='service_orders.serviceorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiated_by', models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager (Client)'), ('SUPPLIER_REPRESENTATIVE', 'Supplier Representative')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING_SUPPLIER', 'Pending Supplier Approval'), ('PENDING_CLIENT', 'Pending Client Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_SUPPLIER', max_length=30)),
                ('outgoing_specialist_id', models.CharField(max_length=50)),
                ('outgoing_specialist_name', models.CharField(max_length=255)),
                ('incoming_specialist_id', models.CharField(max_length=50)),
                ('incoming_specialist_name', models.CharField(max_length=255)),
                ('incoming_specialist_daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('LOW_PERFORMANCE', 'Low Performance'), ('JOB_CHANGE', 'Specialist Job Change'), ('HEALTH_ISSUES', 'Health Issues'), ('PERSONAL_REASONS', 'Personal Reasons'), ('SKILL_MISMATCH', 'Skill Mismatch'), ('CLIENT_REQUEST', 'Client Request'), ('OTHER', 'Other')], max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='service_orders.serviceorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
