# Generated by Django 5.2.9 on 2026-01-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_alter_serviceorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceordersubstitution',
            name='incoming_specialist_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceordersubstitution',
            name='incoming_specialist_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceordersubstitution',
            name='incoming_specialist_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
