# Generated by Django 5.2.9 on 2026-01-20 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('role_name', models.CharField(max_length=128)),
                ('technology', models.CharField(blank=True, max_length=128)),
                ('specialization', models.CharField(blank=True, max_length=64)),
                ('experience_level', models.CharField(choices=[('EXPERT', 'Expert'), ('LEAD', 'Lead'), ('SENIOR', 'Senior'), ('MID', 'Mid'), ('JUNIOR', 'Junior')], default='JUNIOR', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_man_days', models.PositiveIntegerField(blank=True, null=True)),
                ('criteria_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('task_description', models.TextField(blank=True)),
                ('offer_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=128, null=True)),
                ('specialist_id', models.CharField(blank=True, max_length=128, null=True)),
                ('specialist_name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='service_requests.servicerequest')),
            ],
        ),
    ]
