# Generated by Django 5.2.9 on 2026-01-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='process_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
