# Generated by Django 5.2.9 on 2026-01-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequest_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
