# Generated by Django 5.2.9 on 2026-01-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_servicerequest_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='task_id',
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
